// POKEMON ACTIONS
export const SET_POKEMONS = "SET_POKEMONS";
export const ADD_POKEMON_TO_TEAM = "ADD_POKEMON_TO_TEAM";
export const REMOVE_POKEMON_FROM_TEAM = "REMOVE_POKEMON_FROM_TEAM";
export const SET_POKEMON_DETAILS_TO_DISPLAY = "SET_POKEMON_DETAILS_TO_DISPLAY";
export const SET_MESSAGE = "SET_MESSAGE";

// LOG ACTIONS

export const ADD_LOG = 'ADD_LOG';

export const EMPTY_LOGS = 'EMPTY_LOGS';